### ISSUE TITLE
Trouble setting the correct working directory in Jupyter Notebook (jovyan)

### ISSUE THREAD

**Issue by rvinogradov** [ecotner/osrm-blog#5]
Hi, I have setup OSRM using the docker image they provide on their [github page](https://github.com/Project-OSRM/osrm-backend).

When I try to run your jupyter notebook route_analysis.ipynb, I have difficulties setting the correct working directory (I assume that's the directory where I extracted the OSM files to?)
`%cd ~/projects/osrm-mapmatching/amsterdam/`

I get the error:
```
[Errno 2] No such file or directory: '/home/jovyan/projects/osrm-mapmatching/amsterdam/'
/home/jovyan
```
What is the best workaround for this issue?

**Comment by ecotner** [comment]
Hi @rvinogradov it's not really critical that you set the working directory to be able to use OSRM, I only do that in the notebook so that I can import csv's into pandas. You do not interact with the OSRM files at all through python; once you set up the OSRM docker container you treat it like a webserver and make HTTP requests against it. That's what I use the `requests` package for, so you can make [API calls against the server.](http://project-osrm.org/docs/v5.5.1/api/#general-options)

If you want to change your working directory and are having trouble, try using an absolute path rather than relying on `~` to alias to your home directory. Although the error you are getting makes it seem like the directory you're trying to change to does not exist.

**Comment by rvinogradov** [comment]
Thanks for clearing that up, I understood that incorrectly then. 

Forgot to mention that I'm running the notebook in a JupyterHub. So the directory _jovyan_ indeed does not exist.. Anyway, I'm importing my data differently, so I'm closing this issue. I do have another last question though, but will create a new issue for that.
